name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: pip install sphinx-autoapi sphinx_rtd_theme

      - name: Build docs
        working-directory: sphinx-docs
        run: sphinx-build -b html . _build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: sphinx-docs/_build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
